### ISSUE TITLE
Update for Unreal 5.3

### ISSUE THREAD

**Issue by forsenkappa** [chonjay21/AnimVerlet#1]
Hello) Can you please update plugin for Unreal 5.3?

**Comment by chonjay21** [comment]
Ok, I'll try it soon

**Comment by arifakca** [comment]
Hi , could you please update for 5.3?

**Comment by chonjay21** [comment]
Sorry for the delay in the update. Due to personal circumstances, I will update soon.

**Comment by dcms-social** [comment]
Pls update

**Comment by chonjay21** [comment]
Sorry for the late update.
UE 5.3.2 / UE 5.4.3 are now supported in the latest release.
